### ISSUE TITLE
[Support]: Invalid API Key

### ISSUE THREAD

**Issue by devvick** [sinamics/ztnet#780]
### 📝 Inquiry

Similar to #558, except I'm not using standalone npm, nor docker compose, but docker run with custom network (which is functionally equivalent to compose).

Error log when I try to add new network:
```
Dec 02 21:46:52 ztnet-docker[7666]: Database seeded successfully!
Dec 02 21:46:52 ztnet-docker[7666]: Executing command
Dec 02 21:46:52 ztnet-docker[7666]:    ▲ Next.js 15.5.2
Dec 02 21:46:52 ztnet-docker[7666]:    - Local:        http://ztnet:3000
Dec 02 21:46:52 ztnet-docker[7666]:    - Network:      http://ztnet:3000
Dec 02 21:46:52 ztnet-docker[7666]:  ✓ Starting...
Dec 02 21:46:52 ztnet-docker[7666]:  ✓ Ready in 383ms
Dec 02 21:47:00 ztnet-docker[7666]: Error [APIError]:  APIError:  APIError: Invalid API Key (get_controller_status) (network_create)
Dec 02 21:47:00 ztnet-docker[7666]:     at Object.B (.next/server/chunks/1093.js:1:3069)
Dec 02 21:47:00 ztnet-docker[7666]:     at async k (.next/server/chunks/6573.js:1:3347)
Dec 02 21:47:00 ztnet-docker[7666]:     at async (.next/server/chunks/8230.js:20:13767) {
Dec 02 21:47:00 ztnet-docker[7666]:   status: undefined,
Dec 02 21:47:00 ztnet-docker[7666]:   statusText: undefined,
Dec 02 21:47:00 ztnet-docker[7666]:   cause: undefined
Dec 02 21:47:00 ztnet-docker[7666]: }
```
Docker run command:
```
docker run --name ztnet \
    --log-driver=none \
    --network=def0 \
    --hostname=ztnet \
    -v /docker/zerotier:/var/lib/zerotier-one \
    -e "POSTGRES_HOST=postgres" \
    -e "POSTGRES_PORT=5432" \
    -e "POSTGRES_USER=postgres" \
    -e "POSTGRES_PASSWORD=***************" \
    -e "POSTGRES_DB=ztnet" \
    -e "NEXTAUTH_URL=https://ztnet.mydomain.com" \
    -e "NEXTAUTH_SECRET=****************" \
    -e "NEXTAUTH_URL_INTERNAL=http://ztnet:3000" \
    -l "traefik.enable=true" \
    -l "traefik.http.routers.ztnet.entrypoints=websecure" \
    -l "traefik.http.routers.ztnet.rule=HostRegexp(`^ztnet\\..*`)" \
    -l "traefik.http.routers.ztnet.tls=true" \
    -l "traefik.http.routers.ztnet.service=ztnet" \
    -l "traefik.http.services.ztnet.loadbalancer.server.url=http://ztnet:3000" \
    -l "traefik.http.services.ztnet.loadbalancer.passhostheader=false" \
    sinamics/ztnet:latest
```
I set the zyclonite/zerotier:1.14.2 container in the same "def0" network, and tried both ZT_ALLOW_ options:
```
"ZT_ALLOW_MANAGEMENT_FROM=172.18.0.0/16"  # def0 network
"ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0"
```
Right now I'm running it using this run command:
```
docker run --name zerotier \
    --log-driver=none \
    --network=def0 \
    --hostname=zerotier \
    --cap-add=NET_ADMIN \
    --cap-add=SYS_ADMIN \
    -p 9993:9993/udp \
    --device=/dev/net/tun:/dev/net/tun \
    -v /docker/zerotier:/var/lib/zerotier-one \
    -e "ZT_OVERRIDE_LOCAL_CONF=true" \
    -e "ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0" \
    zyclonite/zerotier:1.14.2
```

### 🔖 Version

latest

### 🔧 Deployment Type

- [x] Docker
- [ ] Standalone

### 💻 Operating System

Debian

### 🌐 Browser

Chrome

### 📚 Any Other Information That May Be Helpful

(I can access ztnet.mydomain.com without a problem only if I explicitly set the last 2 traefik labels - I don't know why)
I tried to copy the contents of /var/lib/zerotier/authtoken.secret to the Zerotier Secret field in ZT Controller settings in the app, but that doesn't work either.

All the environment is fresh from scratch.

**Comment by sinamics** [comment]
This has been resolved in latest version.

**Comment by devvick** [comment]
Nope, still doesn't work (image is still `sinamics/ztnet:latest` )
```
Dec 20 18:23:56 ztnet-docker[133727]: All migrations have been successfully applied.
Dec 20 18:23:56 ztnet-docker[133727]: npm notice
Dec 20 18:23:56 ztnet-docker[133727]: npm notice New major version of npm available! 10.7.0 -> 11.7.0
Dec 20 18:23:56 ztnet-docker[133727]: npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.7.0
Dec 20 18:23:56 ztnet-docker[133727]: npm notice To update run: npm install -g npm@11.7.0
Dec 20 18:23:56 ztnet-docker[133727]: npm notice
Dec 20 18:23:56 ztnet-docker[133727]: Migrations applied successfully!
Dec 20 18:23:56 ztnet-docker[133727]: Seeding the database...
Dec 20 18:23:59 ztnet-docker[133727]: Environment variables loaded from .env
Dec 20 18:23:59 ztnet-docker[133727]: ┌─────────────────────────────────────────────────────────┐
Dec 20 18:23:59 ztnet-docker[133727]: │  Update available 6.16.3 -> 7.2.0                       │
Dec 20 18:23:59 ztnet-docker[133727]: │                                                         │
Dec 20 18:23:59 ztnet-docker[133727]: │  This is a major update - please follow the guide at    │
Dec 20 18:23:59 ztnet-docker[133727]: │  https://pris.ly/d/major-version-upgrade                │
Dec 20 18:23:59 ztnet-docker[133727]: │                                                         │
Dec 20 18:23:59 ztnet-docker[133727]: │  Run the following to update                            │
Dec 20 18:23:59 ztnet-docker[133727]: │    npm i -g prisma@latest                               │
Dec 20 18:23:59 ztnet-docker[133727]: │    npm i @prisma/client@latest                          │
Dec 20 18:23:59 ztnet-docker[133727]: └─────────────────────────────────────────────────────────┘
Dec 20 18:23:59 ztnet-docker[133727]: Database seeded successfully!
Dec 20 18:23:59 ztnet-docker[133727]: Executing command
Dec 20 18:24:00 ztnet-docker[133727]:    ▲ Next.js 16.0.10
Dec 20 18:24:00 ztnet-docker[133727]:    - Local:         http://ztnet:3000
Dec 20 18:24:00 ztnet-docker[133727]:    - Network:       http://ztnet:3000
Dec 20 18:24:00 ztnet-docker[133727]:  ✓ Starting...
Dec 20 18:24:01 ztnet-docker[133727]:  ✓ Ready in 429ms
Dec 20 18:24:28 ztnet-docker[133727]: Error [APIError]:  APIError:  APIError: Invalid API Key (get_controller_status) (network_create)
Dec 20 18:24:28 ztnet-docker[133727]:     at Module.k [as network_create] (.next/server/chunks/[root-of-the-server]__7956cf65._.js:1:8862)
Dec 20 18:24:28 ztnet-docker[133727]:     at async d (.next/server/chunks/[root-of-the-server]__dd195d76._.js:1:5876)
Dec 20 18:24:28 ztnet-docker[133727]:     at async (.next/server/chunks/[root-of-the-server]__07addd78._.js:20:14798) {
Dec 20 18:24:28 ztnet-docker[133727]:   statusText: undefined,
Dec 20 18:24:28 ztnet-docker[133727]:   status: undefined,
Dec 20 18:24:28 ztnet-docker[133727]:   cause: undefined
Dec 20 18:24:28 ztnet-docker[133727]: }
```

**Comment by sinamics** [comment]
i think this is a seperate issue. 
try adding this to ztnet env `-e "ZT_ADDR=http://zerotier:9993"` and `-e "ZT_SECRET=token_from_authtoken_secret`. Also make sure you can ping zerotier from ztnet container.
if this does not work, make sure you have access to zerotier-one folder, `docker exec ztnet ls -la /var/lib/zerotier-one`.

**Comment by devvick** [comment]
Still the same error:
```
Dec 20 20:15:51 ztnet-docker[4136]: Error [APIError]:  APIError:  APIError: Invalid API Key (get_controller_status) (network_create)
Dec 20 20:15:51 ztnet-docker[4136]:     at Module.k [as network_create] (.next/server/chunks/[root-of-the-server]__7956cf65._.js:1:8862)
Dec 20 20:15:51 ztnet-docker[4136]:     at async d (.next/server/chunks/[root-of-the-server]__dd195d76._.js:1:5876)
Dec 20 20:15:51 ztnet-docker[4136]:     at async (.next/server/chunks/[root-of-the-server]__07addd78._.js:20:14798) {
Dec 20 20:15:51 ztnet-docker[4136]:   statusText: undefined,
Dec 20 20:15:51 ztnet-docker[4136]:   status: undefined,
Dec 20 20:15:51 ztnet-docker[4136]:   cause: undefined
Dec 20 20:15:51 ztnet-docker[4136]: }
```
I added both envvars and tested mount and connectivity - all working:
```
$ docker exec ztnet ls -al /var/lib/zerotier-one
total 60
drwxr-xr-x 4 root root  4096 Dec 20 20:15 .
drwxr-xr-x 1 root root  4096 Dec 13 08:59 ..
-rw------- 1 root root    24 Dec 20 18:23 authtoken.secret
drwx------ 4 root root  4096 Dec 20 18:23 controller.d
-rw-r--r-- 1 root root   141 Dec 20 18:23 identity.public
-rw------- 1 root root   270 Dec 20 18:23 identity.secret
-rw-r--r-- 1 root root   220 Dec 20 20:15 local.conf
-rw-r--r-- 1 root root 10783 Dec 20 20:16 metrics.prom
-rw------- 1 root root    24 Dec 20 18:23 metricstoken.secret
drwxr-xr-x 2 root root  4096 Dec 20 18:37 peers.d
-rw-r--r-- 1 root root   570 Dec 20 18:23 planet
-rw-r--r-- 1 root root     1 Dec 20 20:15 zerotier-one.pid
-rw-r--r-- 1 root root     4 Dec 20 20:15 zerotier-one.port

$ docker exec -it ztnet /bin/bash
root@ztnet:/app# curl -v http://zerotier:9993
*   Trying [fd11::6]:9993...
* Connected to zerotier (fd11::6) port 9993 (#0)
> GET / HTTP/1.1
> Host: zerotier:9993
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Content-Length: 2
< Content-Type: application/json
< Keep-Alive: timeout=5, max=5
< 
* Connection #0 to host zerotier left intact
```

**Comment by sinamics** [comment]
Try these command inside ztnet container and see if you get data from the zt api.
```
TOKEN=$(sudo cat /var/lib/zerotier-one/authtoken.secret)
curl -H "X-ZT1-Auth: $TOKEN" http://zerotier:9993/status
```

**Comment by devvick** [comment]
Thank you for this command. I just have noticed that curl is using IPv6 address, which is not in the zerotier container allowlist. IPv4 works:
```
root@ztnet:/app# curl -v -H "X-ZT1-Auth: $TOKEN" http://zerotier:9993/status
*   Trying [fd11::6]:9993...
* Connected to zerotier (fd11::6) port 9993 (#0)
> GET /status HTTP/1.1
> Host: zerotier:9993
> User-Agent: curl/7.88.1
> Accept: */*
> X-ZT1-Auth: *******************
> 
< HTTP/1.1 401 Unauthorized
< Content-Length: 2
< Content-Type: application/json
< Keep-Alive: timeout=5, max=5
< 
* Connection #0 to host zerotier left intact
root@ztnet:/app# curl -v -H "X-ZT1-Auth: $TOKEN" http://172.18.0.6:9993/status
*   Trying 172.18.0.6:9993...
* Connected to 172.18.0.6 (172.18.0.6) port 9993 (#0)
> GET /status HTTP/1.1
> Host: 172.18.0.6:9993
> User-Agent: curl/7.88.1
> Accept: */*
> X-ZT1-Auth: *******************
> 
< HTTP/1.1 200 OK
< Content-Length: 993
< Content-Type: application/json
< Keep-Alive: timeout=5, max=5
< 
* Connection #0 to host 172.18.0.6 left intact
(...)
```
This is my fault indeed: I explicitly enable IPv6 in my container setups.
If IPv6 allowlist won't work for zerotier, I'll switch to IPv4 for the setup.

EDIT: Adding IPv6 address to ZT_ALLOW_MANAGEMENT_FROM works!
